apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: upteck
  labels:
    app: mysql
    tier: databas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: database
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: UPTECK
        - name: MYSQL_USER
          value: rayen
        - name: MYSQL_PASSWORD
          value: rayen
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: "0.5" # Define the CPU limit
            memory: "512Mi" # Define the memory limit
          requests:
            cpu: "0.1" # Define the CPU request
            memory: "256Mi" # Define the memory request
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
