apiVersion: v1
kind: Service
metadata:
  name: upteck-back-service
  namespace: upteck
spec:
  selector:
    app: upteck-back
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer


